In [11]:
# 26 february

In [12]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
# to print the data types of both the variables.

In [13]:
import numpy as np

In [14]:
list1= ['1','2','3','4','5']

array_list = np.array(object = list)
print(type(list1))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
# Array stores elements of similar types. If we try to store elements of different types, it will throw an error.
# We can store elements of different types in the list.

In [16]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and 
# arr_list.

In [17]:
list1= [1,2.5,3,4.023,5]
print("type of list")
array_list = np.array(object = list1)
for i in list1:
    print(type(i))
    
print("type of array_list")
for j in array_list:
    print(type(j))

type of list
<class 'int'>
<class 'float'>
<class 'int'>
<class 'float'>
<class 'int'>
type of array_list
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [18]:
# Q3. Considering the following changes in the variable, array_list.
# Will there be any difference in the data type of the elements present in both the variables, list_ and 
# arra_list? If so then print the data types of each and every element present in both the variables, list_ 
# and arra_list.

In [19]:
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_, dtype = int)

In [20]:
array_list

array([1, 2, 3, 4, 5])

In [21]:
# Yes the array_list have all elements integer type.
print("type of list_ ")
for i in list_:
    print(type(i))
    
print("type of array_list ")
for i in array_list:
    print(type(i))

type of list_ 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
type of array_list 
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [22]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [23]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [24]:
num_array.shape

(2, 3)

In [25]:
num_array.size

6

In [26]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
# creation function.

In [27]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [29]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])